### PR TITLE
add SendReply method

### LINKED ISSUE #10: Add the ability to reply inline
Many chat applications have the ability to reply to an existing message as an inline comment. This API should support that behaviour.

Current behaviour: all replies are top level messages.
Desired behaviour: add the ability to reply to a particular comment. Default implementation should allow this **not** to be implemented on any platforms that do not support it. On those platforms they should degrade gracefully into a top-level message.
Ideally, threads should be obtainable from either any top-level message or any reply to those threads, to allow the reply to be directly to a top-level message, or as a reply within one of these threads.

Related to [this](https://github.com/GlobalX/GlobalX.ChatBots.WebexTeams/issues/11).

### PR DESCRIPTION
**Pull request by jimcullenaus**
Fixes #10

### CODE REVIEW

**Comment by Lauraducky** [comment]
Should probably add Id to the Message model so this can actually be used

**Comment by jimcullenaus** [comment]
Hmm, that raises an interesting point. [ParentId](https://developer.webex.com/docs/api/v1/messages/list-messages) is the property Webex uses for this feature. Do you think it would be better to be explicit about parentId in this way, or to implicitly roll it into the existing SendMessage method by having a reply by done if the parentId property is set to a non-null value?

If the latter, what is the best way to *document* this behaviour?

**Comment by Lauraducky** [comment]
Good point. What we *could* do is treat this similarly to direct vs group messages, and simply use parent id in the message model to send reply messages. Another question to consider: How does Webex treat parentId if we set the parentId to the id of a reply message? Does it need to be set to the id of the parent of that reply message?

**Comment by Lauraducky** [comment]
Good point. I like that since it's similar to the way we treat group vs direct messages. Another question to consider: How does Webex treat parentId if we set the parentId to the id of a reply message? Does it need to be set to the id of the parent of that reply message?

**Comment by jimcullenaus** [comment]
Not sure how Webex works in that respect. Will need to do investigations into it during the Webex implementation of this library change.

However, my proposal is that that should not affect how this API gets designed. The Webex library should handle it gracefully by substituting the user-provided parentId with the one Webex needs for it to work, if that's necessary to make it work.

**Review by Evangelinexx — APPROVED** [review]

**Review by Chromadream — APPROVED** [review]

**Review by Lauraducky — APPROVED** [review]

**Pull request merged**
